FROM node:18.16.0

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm audit fix

RUN npm audit fix --force

COPY . .

EXPOSE 4444

CMD ["npm", "run", "dev"]
